### ISSUE TITLE
NPE when decrypting a BIP38 encoded private key that was passed via intent extra

### ISSUE THREAD

**Issue by schildbach** [schildbach/bitcoin-wallet#286]
java.lang.NullPointerException
at org.bitcoinj.core.Address.<init>(Address.java:87)
at org.bitcoinj.core.ECKey.toAddress(ECKey.java:514)
at org.bitcoinj.crypto.BIP38PrivateKey.decrypt(BIP38PrivateKey.java:94)
at de.schildbach.wallet.ui.send.DecodePrivateKeyTask$1.run(DecodePrivateKeyTask.java:49)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by palejaga** [comment]
Doble ng #
